### ISSUE TITLE
Error encountered out of nowhere

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/pivottiles7#32]
![image](https://user-images.githubusercontent.com/35781691/101180568-6c79b380-3654-11eb-8f55-4d3fd4d5616e.png)

Sitepages did not have unique permissions and all news pages had categories.

**Comment by mikezimm** [comment]
I found that if you 
1. select Site Pages or Site Pages News in the **Basic Column Mapping** section 
2. and Build from TileCategory column in **Custom Categories** column

The BuildTileColletion.ts was trying to push a custom category "News" to the categories property (which was a string because step 1 above would set the Tile Category to the Author/Title property).

## To make a long story short ( fix )
I made it so that the category prop was converted to an array if it was previoulys a text value.

Note that I also discovered that some previous features no longer work (due to custom categories)... like if you CTRL-Click the search box and type "created" or "modified".

## Step 1 above
![image](https://user-images.githubusercontent.com/49648086/101197286-e8add000-362f-11eb-8b35-18abde8fb7f4.png)

## Step 2 above
![image](https://user-images.githubusercontent.com/49648086/101197300-ed728400-362f-11eb-821b-afefc36cfbee.png)
